### PR TITLE
Add instructions to Terra notebook 

### PR DESCRIPTION
**Pull request by vdauwera**
Building on #108 from @korikuzma — addressing request for additional info from @ahwagner

### CODE REVIEW

**Review by korikuzma — APPROVED** [review]
Looks good to me! Thanks for adding these additions.

**Comment by wesleygoar** [comment]
@vdauwera I am not able to access the workspace to test it. 
Screen Shot 2022-09-16 at 8 31 13 AM

**Comment by vdauwera** [comment]
> @vdauwera I am not able to access the workspace to test it. Screen Shot 2022-09-16 at 8 31 13 AM

I'll need a couple of days to get the workspace be made fully public. In the meantime I can share the workspace with you if you send me your email address. Or @korikuzma can share it with you as well.

**Comment by wesleygoar** [comment]
@vdauwera great! Alex wanted me to test it before Plenary. My email is wesley.goar@nationwidechildrens.org.

**Review by larrybabb — APPROVED** [review]
looks good to me. deferring to others for final say

**Comment by korikuzma** [comment]
@wesleygoar @ahwagner I shared to your NCH emails

**Comment by vdauwera** [comment]
> @vdauwera great! Alex wanted me to test it before Plenary. My email is [wesley.goar@nationwidechildrens.org](mailto:wesley.goar@nationwidechildrens.org).

I made you a writer and activated the "can compute" option, so you should be able to spin up an environment under the workspace's billing project without having to clone the workspace to a project your lab owns. This does mean that any changes you make to any of the notebooks will be visible to everyone. Let me know if you need any pointers.

**Comment by korikuzma** [comment]
@wesleygoar confirmed that he was able to get it to work. Are we good to merge @ahwagner ?

**Review by ahwagner — APPROVED** [review]

**Pull request merged**
