### PR TITLE
docs: update vrs-python and vrs version correspondences

### PR DESCRIPTION
**Pull request by korikuzma**
@larrybabb Proposing to only list the versions/branches that are maintained in VRS-Python

### CODE REVIEW

**Review by larrybabb — APPROVED** [review]
+1 great start

**Comment by korikuzma** [comment]
I will wait to open until #314 and #313 are merged

**Comment by jsstevenson** [comment]
@korikuzma does this close #292?

**Comment by korikuzma** [comment]
I'm going to close this and open a new PR. I based this off of the 1.x branch, but it should be 2.x

**Pull request closed without merging**
