### PR TITLE
fix: revert Pydantic custom serializer

### PR DESCRIPTION
**Pull request by korikuzma**
* The Pydantic custom serializer resulted in `model_dump` to only include minimal fields for ga4gh serialization. This caused issues in downstream apps that leverage FastAPI

### CODE REVIEW

**Comment by korikuzma** [comment]
Oh, I forgot to check `__hash__`

**Review by ahwagner — APPROVED** [review]
Yeah, I guess... 😞 

It makes sense to not muck about with the "as json" return, though ideally we would be able to leverage the Rust code in pydantic core for serialization, and not need to introduce a new dependency.

That said, usability is secondary to performance, so I agree this is an improvement. 👍

**Comment by korikuzma** [comment]
@ahwagner I updated the __hash__. Lmk if this is what you think it should be?

**Comment by ahwagner** [comment]
@korikuzma what you wrote is fine. `__hash__` is helpful for comparison operations and indexing, but doesn't play a role in any of the GA4GH identifier methods as far as I can remember. That this now reflects the `ga4gh_digest` method takes a little more compute that what might be strictly necessary, but I doubt it will be meaningful in terms of regular usage. I think we can move forward as is.

**Comment by korikuzma** [comment]
@ahwagner I can revert and use a different hash function, I was just basing off of the current implementation in `main`. @theferrit32 originally made the issue in #225 , so do you have any thoughts?

**Comment by theferrit32** [comment]
@korikuzma I think this is enough for #225 as long as the only types that will be in arrays with `uniqueItems: true` in the schema are identifiable ones. Actually at the moment I'm not seeing any `uniqueItems: true` in the schemas. I think previously it was used in the Haplotype and Genotype classes.

**Comment by korikuzma** [comment]
@theferrit32 ok, I will go ahead and merge and close #225

**Pull request merged**
