### PR TITLE
cicd: delete stale action

### LINKED ISSUE #287: Remove stale action
As far as I can tell, the stale action has not, at least in recent years, actually closed an issue -- all closures have been manual (mostly by @korikuzma and @theferrit32). On the flip side, we've currently marked almost every open issue as `stale-exempt`. Is this action still a useful part of the workflow? Would it make sense to at least alter the configuration (maybe lengthen `days-before-issue-stale`) if not remove it entirely?

### PR DESCRIPTION
**Pull request by korikuzma**
close #287

Will also remove the stale labels

### CODE REVIEW

**Review by jsstevenson — APPROVED** [review]

**Comment by korikuzma** [comment]
@theferrit32 @toneillbroad want to make sure you two are okay with deleting this action before merging

**Comment by jsstevenson** [comment]
I want to mark this PR as stale

**Review by larrybabb — APPROVED** [review]
+1

**Comment by larrybabb** [comment]
I merged before @theferrit32 and @toneillbroad weighed in. If they want it back I'll undo it.

**Comment by korikuzma** [comment]
@larrybabb I made a comment on slack, but I think it would be good to get in the habit of squashing + merging PRs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

**Comment by larrybabb** [comment]
@korikuzma sorry I missed it. I will do that from now on.

**Comment by korikuzma** [comment]
@larrybabb no worries! Maybe it makes sense to include a "contributing" doc for our development practices

**Comment by larrybabb** [comment]
@korikuzma see [here](https://github.com/ga4gh/vrs-python/issues/300). If you have ideas on how to start this, please feel free to draft it.  If not, let's mention it the next time we all convene after the break and see if we can put together something simple (or copy from some other site that's already done this).

**Pull request merged**
