### PR TITLE
fix: add rle_seq_limit to AlleleTranslator

### LINKED ISSUE #344: ‘NoneType’ object has no attribute ‘root’ when getting HGVS from Python dict
I’m trying to get an hgvs ID from a python dict, but I’m running into problems when it does validation of `vo.state.sequence.root`, here’s the code I’m using…

```
allele = models.Allele(**allele_dict)
_id = translator.translate_to(allele, fmt)
```

what the allele_dict looks like…

```
{
  "id": "ga4gh:VA.VzxoidAEEbcLu12HOOxUYo4fuXE4A5iv",
  "type": "Allele",
  "location": {
    "id": "ga4gh:SL.fM4OgBuELjPWKeQSCjVKdcTJvas-H5uH",
    "type": "SequenceLocation",
    "sequenceReference": {
      "type": "SequenceReference",
      "refgetAccession": "SQ.vWwFhJ5lQDMhh-czg06YtlWqu0lvFAZV"
    },
    "start": 262338,
    "end": 262339
  },
  "state": {
    "type": "ReferenceLengthExpression",
    "length": 410,
    "repeatSubunitLength": 409
  }
}
```

and the error:
> File ~/.local/lib/python3.10/site-packages/ga4gh/vrs/extras/translator.py:144, in Translator.translate_to(self, vo, fmt)
>     142 “”"translate vrs object `vo` to named format `fmt`“”"
>     143 t = [self.to](http://self.to/)_translators[fmt]
> --> 144 return t(vo)
> File ~/.local/lib/python3.10/site-packages/ga4gh/vrs/extras/translator.py:523, in AlleleTranslator._to_hgvs(self, vo, namespace)
>     518         start += 1
>     519     ival = hgvs.location.Interval(
>     520         start=hgvs.location.SimplePosition(start),
>     521         end=hgvs.location.SimplePosition(end)
>     522     )
> --> 523     alt = str(vo.state.sequence.root) or None  # “” => None
>     524     edit = hgvs.edit.NARefAlt(ref=ref, alt=alt)
>     526 posedit = hgvs.posedit.PosEdit(pos=ival, edit=edit)
> AttributeError: ‘NoneType’ object has no attribute ‘root’

Would love to know how to fix this, thanks!

### PR DESCRIPTION
**Pull request by korikuzma**
close #344 . Setting as high priority since @quinnwai said it was blocking

@quinnwai The reason why your example was failing is because the `len(alt) > 50`, where 50 was the limit we had set. This PR allows `rle_seq_limit` to be passed

### CODE REVIEW

**Comment by korikuzma** [comment]
@ga4gh/vrs-python-maintainers Is someone able to review this so I can make a pypi release for @quinnwai?

**Review by larrybabb — APPROVED** [review]
+1

**Comment by larrybabb** [comment]
@korikuzma was it alright that I merged this? I keep forgetting if that's the job of the approver or the developer?

**Comment by korikuzma** [comment]
@larrybabb Yup! I think we should have a protocol for this

**Pull request merged**
