### PR TITLE
#113: update VRS-Python with VRS Genotype model

### PR DESCRIPTION
**Pull request by ahwagner**
This PR addresses #113 and adds supporting example notebooks.

### CODE REVIEW

**Comment by korikuzma** [comment]
Once [this](https://github.com/ga4gh/vrs/pull/407) PR gets merged, we should update the VRS submodules and we should be good to merge.

**Comment by korikuzma** [comment]
@ahwagner tests now pass. You said you'd work on genotype notebook? Should we create a new issue for this or do you want to work off this PR?

**Comment by ahwagner** [comment]
I've added #117 as a separate issue to address later this week.

**Review by larrybabb — APPROVED** [review]
ship it.

**Pull request merged**
