### PR TITLE
feat: dockerize vrs-python

### LINKED ISSUE #119: Containerize + provide endpoint for VCF / VRS annotation

### PR DESCRIPTION
**Pull request by korikuzma**
Close #119 

Creates a docker image for vrs-python. I'm still pretty new to working with Docker, so any feedback is very appreciated. This work was mainly so that collaborators could run the VCF VRS Annotation tool. I've made it so that you can use the Docker CLI to run the commands. Data will need to be exported to `/data` for it to persist.

### CODE REVIEW

**Comment by korikuzma** [comment]
I also just build the docker image directly inside of docker compose. We're still waiting to hear back from the GA4GH team on setting up a repo in the ga4gh docker account. So down the line, we can use a ga4gh/vrs-python versioned image

**Comment by ahwagner** [comment]
@reece I think your experience with containerizing the upstream tools for this might give you some unique insight into how this was put together.

**Comment by ahwagner** [comment]
I checked out this branch and tried to spin up docker-compose, received the following error:

image

**Comment by korikuzma** [comment]
> I checked out this branch and tried to spin up docker-compose, received the following error:
> 
> image

Hmmm... I did not get this error on my end. What version of docker are you using? I'm using `20.10.17, build 100c701`.

**Comment by korikuzma** [comment]
@ahwagner updated to `Docker version 20.10.21, build baeda1f` and it seems to work for me.

**Comment by reece** [comment]
Sorry... just saw this PR. Will try to look tonight.

**Comment by korikuzma** [comment]
@reece Thanks, really appreciate any feedback you can give! Let me know if you have any questions.

**Comment by reece** [comment]
Hi @korikuzma : It would be helpful to hear what you're trying to build. 

I *think* your goal is to be able to run the vcf annotator on the command line.  I see two routes to that:

1) Bring up the data stack (seqrepo + seqrepo-rest-service + uta), then connect to the data stack via host networking. This will give the most CLI-like behavior.  The CLI could be a python package (e.g., pip install ga4gh-vrs) or a docker image. The advantage of a python package is a better CLI experience; the advantage of a docker image is that you can pre-package all of the ga4gh-vrs python dependencies.
2) Include anyvar in the docker compose stack. Annotate variants individually via a REST interface.

I recommend that you start with ga4gh-vrs as a python package.

**Comment by korikuzma** [comment]
Converted to draft since we're still figuring out requirements.

**Comment by korikuzma** [comment]
@reece once we finalize requirements, I'll re-request your review

**Comment by sjahl** [comment]
Hi @korikuzma 

> We have collaborators who would like to annotate the gnomAD data using the VCF Annotator. They've requested that we create a vrs-python image to use in their pipeline.
> 
> I'm not sure if the interactive Docker CLI is the end goal for their use case, but this was my first step since I'm just getting familiar with Docker. I'm still waiting on a response on how exactly they want to use the Docker image.

@ch-kr asked me to take a look at this since I have some familiarity with Docker. The dockerfile itself is pretty straightforward and what you've written here looks good to me.

In terms of our use case, it could potentially be useful to have a published repository available that could be used for creating other images based on it (e.g. `FROM ga4gh/vrs-python:1.0.0`). But, I think from my perspective, it's probably best for us to just create our own docker images, and install vrs from PyPI alongside the other utilities that we use in our pipelines, so I don't know how much utility a published image will have for us.

In terms of your own packaging requirements, it may make sense for you to provide a CLI-type image like the one you have here, just to have an easy way for people to install it and get started. There are plenty of github Actions available (https://github.com/docker/build-push-action) that could be used for publishing new images alongside your PyPI releases.

**Comment by korikuzma** [comment]
@sjahl Awesome, thanks! @ahwagner I'm going to close this PR for now and revisit if needed.

**Pull request closed without merging**
